### ISSUE TITLE
Add support for variable bitrate for video (currently it is constant).

### ISSUE THREAD

**Issue by nataliausoltseva** [nataliausoltseva/VideoClipper#8]
Allow a user to choose a variable bitrate for video. Currently we are only doing it for audio. You will need to pass the variable bitrate after calling video codec.

**Comment by AndrewTG5** [comment]
Still passes both constant and variable bitrate to FFMPEG

**Comment by AndrewTG5** [comment]
Resolved by [014d5c2](https://github.com/nataliausoltseva/VideoClipper/commit/014d5c25ead1dcf0a25ed851e460695598c4d3a9)
